name: CI

on: [push, pull_request]

env:
  LS_HS_VERSION: 45ff0e1

jobs:
  linux_tests:
    runs-on: ubuntu-18.04
    # latest
    container:
      image: chapel/chapel # or chapel/chapel-gasnet-smp if you want multi-locale
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y --no-install-recommends libnuma-dev libgmp-dev libffi-dev patchelf bzip2 unzip

        wget -q https://github.com/twesterhout/lattice-symmetries-haskell/releases/download/v0.0.1/lattice-symmetries-haskell-${LS_HS_VERSION}-ubuntu-18.04.tar.bz2
        tar -xf lattice-symmetries-haskell-${LS_HS_VERSION}-ubuntu-18.04.tar.bz2
        mv lattice-symmetries-haskell-${LS_HS_VERSION} third_party
        # patchelf --set-rpath '$ORIGIN' third_party/lib/liblattice_symmetries_haskell.so
        ldd third_party/lib/liblattice_symmetries_haskell.so
    - name: Build Application
      run: |
        make
    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=$PWD/third_party/lib:$LD_LIBRARY_PATH
        bin/Example01

  mac_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew install chapel

        wget -q https://github.com/twesterhout/lattice-symmetries-haskell/releases/download/v0.0.1/lattice-symmetries-haskell-${LS_HS_VERSION}-macos-latest.tar.bz2
        tar -xf lattice-symmetries-haskell-${LS_HS_VERSION}-macos-latest.tar.bz2
        mv lattice-symmetries-haskell-${LS_HS_VERSION} third_party
        otool -L third_party/lib/liblattice_symmetries_haskell.dylib
    - name: Build Application
      run: |
        make
    - name: Run tests
      run: |
        export DYLD_LIBRARY_PATH=$PWD/third_party/lib:$DYLD_LIBRARY_PATH
        bin/Example01
