name: CI

on: [push, pull_request]

jobs:
  linux_tests:
    runs-on: ubuntu-latest
    container:
      image: chapel/chapel # or chapel/chapel-gasnet-smp if you want multi-locale
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y --no-install-recommends libnuma-dev libffi-dev libgmp-dev bzip2

        wget -q https://github.com/twesterhout/distributed-matvec/releases/download/v0.0.2/chapel-dependencies-ubuntu-18.04.tar.bz2
        tar -xf chapel-dependencies-ubuntu-18.04.tar.bz2
        mv release third_party
    - name: Build Application
      run: |
        make
    - name: Run tests
      run: |
        bin/Example01

  mac_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew install chapel libffi

        wget -q https://github.com/twesterhout/distributed-matvec/releases/download/v0.0.2/chapel-dependencies-macos-latest.tar.bz2
        tar -xf chapel-dependencies-macos-latest.tar.bz2
        mv release third_party
        otool -l third_party/lib/liblattice_symmetries_core.dylib
        otool -l third_party/lib/liblattice_symmetries_haskell.dylib
    - name: Build Application
      run: |
        make
    - name: Run tests
      run: |
        export DYLD_LIBRARY_PATH=$PWD/third_party/lib:$DYLD_LIBRARY_PATH
        bin/Example01
